# Don't run CI for this config yet. We're not ready to move official builds on to Azure Pipelines
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_x64
    jobDisplayName: 'Tests: Helix x64'
    agentOs: Windows
    timeoutInMinutes: 240
    steps:
    - script: .\restore.cmd -ci
      displayName: Restore
      
    # Build the x86 shared framework
    # TODO: make it possible to build for one Windows architecture at a time
    # This is going to actually build x86 native assets. See https://github.com/aspnet/AspNetCore/issues/7196
    - script: ./build.cmd
              -ci
              -arch x86
              -pack
              -all
              -buildNative
              -noBuildJava
              /p:OnlyPackPlatformSpecificPackages=true
              /bl:artifacts/log/build.x86.binlog
              $(_BuildArgs)
      displayName: Build x86 shared fx
      
    - script: .\build.cmd -ci -NoRestore -test -projects eng\helix\helix.proj /p:IsHelixJob=true /p:BuildAllProjects=true /p:BuildNative=true -bl
      displayName: Run build.cmd helix target
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Windows_Packages
      path: artifacts/packages/    
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
